//------------------------------------------------------------------------------
// <auto-generated>
//   This file is auto-generated and should not be edited directly. If you want
//   to make changes to this file, you can do so by editing the underlying file
//   at T4Demo\Model\Status.tt
// </auto-generated>
//------------------------------------------------------------------------------
const Status = Object.freeze({
    STARTED: 1,
    COMPLETED: 2,
    ERROR: 3
});
