//------------------------------------------------------------------------------
// <auto-generated>
//   This file is auto-generated and should not be edited directly. If you want
//   to make changes to this file, you can do so by editing the underlying file
//   at T4Demo\Model\Status.tt
// </auto-generated>
//------------------------------------------------------------------------------
public enum Status {
    Started = 1,
    Completed = 2,
    Error = 3
}
